import Head from 'next/head'
import Image from 'next/image'


import { Box, Grid, Typography } from '@mui/material'

//json
import blogs from "../public/assets/json/blogs"

//component
import Blog from "../components/blog"

//react 
import { useEffect } from 'react'


export default function Home({ articles }) {
  
  let hookedBlogs = articles.items
  console.log(articles)
    
  let includes = articles.includes.Entry
  

  

  return (
    <>
      <Head>
        <title>Hooked</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box className="home-container">
        <Grid comonent="header" container sx={{px: 3, py: 10, backgroundColor: "black", color: 'white', display: 'flex', flexDirection: 'column'}}>
          <Typography variant="h1" sx={{mb: 2, fontSize: {laptop: '5rem'}}}>
            Hooked Blogs
          </Typography>   

          <Typography variant="body1" sx={{color: 'grey.500'}}>
            Get everything <b>webdev</b>
          </Typography>       
        </Grid>

        <Grid component="main" container sx={{py: {phone: 3, tablet: 6, laptop: 10}}}>
          {
            hookedBlogs.map(({fields, sys}) => {
              if(fields.trending === false){
                return (
                  <Blog key={sys.id } id={sys.id} fields={fields} includes={includes} />
                )
              }   

              return           
            })
          }
        </Grid>       
      </Box>      
    </>
  )
}

export async function getServerSideProps(){

  let api = `https://cdn.contentful.com/spaces/${process.env.NEXT_PUBLIC_CONTENTFUL_SPACE_ID}/environments/master/entries?access_token=${process.env.NEXT_PUBLIC_CONTENTFUL_CDA_APIKEY}&content_type=blogs`

  let articles = null

    const res = await fetch(api)
    const data = await res.json()
    articles = data
      
  console.log(articles)
  


  return{
    props: {
      articles
    }
  }

}

``